# Generated by Django 4.2.7 on 2023-10-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_cat_image'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
