# Generated by Django 4.2.7 on 2023-11-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_likes'),
    ]

 
