# Generated by Django 4.2.7 on 2024-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1_alt_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_alt_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_alt_text',
            field=models.TextField(null=True),
        ),
    ]
